// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// MinersColumns holds the columns for the "miners" table.
	MinersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "state_root", Type: field.TypeString},
		{Name: "miner_id", Type: field.TypeString, Unique: true},
		{Name: "owner_addr", Type: field.TypeString},
		{Name: "worker_addr", Type: field.TypeString},
		{Name: "peer_id", Type: field.TypeString},
		{Name: "sector_size", Type: field.TypeString},
	}
	// MinersTable holds the schema information for the "miners" table.
	MinersTable = &schema.Table{
		Name:        "miners",
		Columns:     MinersColumns,
		PrimaryKey:  []*schema.Column{MinersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MinersTable,
	}
)

func init() {
}
