// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/frrist/specs-actors-model/ent/miner"
	"github.com/frrist/specs-actors-model/ent/schema"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	minerFields := schema.Miner{}.Fields()
	_ = minerFields
	// minerDescMinerID is the schema descriptor for miner_id field.
	minerDescMinerID := minerFields[1].Descriptor()
	// miner.MinerIDValidator is a validator for the "miner_id" field. It is called by the builders before save.
	miner.MinerIDValidator = minerDescMinerID.Validators[0].(func(string) error)
	// minerDescOwnerAddr is the schema descriptor for owner_addr field.
	minerDescOwnerAddr := minerFields[2].Descriptor()
	// miner.OwnerAddrValidator is a validator for the "owner_addr" field. It is called by the builders before save.
	miner.OwnerAddrValidator = minerDescOwnerAddr.Validators[0].(func(string) error)
	// minerDescWorkerAddr is the schema descriptor for worker_addr field.
	minerDescWorkerAddr := minerFields[3].Descriptor()
	// miner.WorkerAddrValidator is a validator for the "worker_addr" field. It is called by the builders before save.
	miner.WorkerAddrValidator = minerDescWorkerAddr.Validators[0].(func(string) error)
	// minerDescSectorSize is the schema descriptor for sector_size field.
	minerDescSectorSize := minerFields[5].Descriptor()
	// miner.SectorSizeValidator is a validator for the "sector_size" field. It is called by the builders before save.
	miner.SectorSizeValidator = minerDescSectorSize.Validators[0].(func(string) error)
}
