// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Miner is the predicate function for miner builders.
type Miner func(*sql.Selector)
